#!/bin/bash
#
# This Bash script opens the command line SQL shell for CockroachDB using the
# root certificates.
#
# Usage: ./runsql [filename]
#   filename: Path to a file with SQL commands to execute

COCKROACH_CERTS=~/cockroach/certs

COMMAND="cockroach sql
--ca-cert=$COCKROACH_CERTS/ca.cert
--cert=$COCKROACH_CERTS/root.cert
--key=$COCKROACH_CERTS/root.key"

if [ "$#" -gt 0 ]; then
  eval ${COMMAND} < $1
else
  eval ${COMMAND}
fi
