#!/bin/bash

COCKROACH_CERTS=~/cockroach/certs

COMMAND="cockroach sql
--ca-cert=$COCKROACH_CERTS/ca.cert
--cert=$COCKROACH_CERTS/root.cert
--key=$COCKROACH_CERTS/root.key"

if [ "$#" -gt 0 ]; then
  eval ${COMMAND} < $1
else
  eval ${COMMAND}
fi
